### ISSUE TITLE
请问本项目的图像融合方法适用于yolov8pose吗

### ISSUE THREAD

**Issue by alubabaobao** [wandahangFY/YOLO-MIF#9]
能原封不动的照着改吗，能跑通yolov8pose吗

**Comment by wandahangFY** [comment]
v8 pose 和 segment还有obb部分，我在下个月发出来，最近忙着中期答辩和项目。除了教程以外，还需要更改pose部分的代码，这个项目最初只考虑到了detect
 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:alubabaobao< ***@***.***>Date:2024-12-16 20:49:06To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Subscribed< ***@***.***>Subject:[wandahangFY/YOLO-MIF] 请问本项目的图像融合方法适用于yolov8pose吗 (Issue #9)
能原封不动的照着改吗，能跑通yolov8pose吗

**Comment by alubabaobao** [comment]
前来催更！非常希望能跟着作者学习关于图像融合pose部分的改动。谢谢~

**Comment by wandahangFY** [comment]
我测试了一下，RGBT的pose和seg训练是没有问题的，推理部分可以先把plot绘图给注释掉，保存result，用自定义的脚步来绘图，最迟周末会更新完这部分
 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:alubabaobao< ***@***.***>Date:2025-01-06 19:05:32To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Dahang Wan< ***@***.***>、Comment< ***@***.***>Subject:Re: [wandahangFY/YOLO-MIF] 请问本项目的图像融合方法适用于yolov8pose吗 (Issue #9)
前来催更！非常希望能跟着作者学习关于图像融合pose部分的改动。谢谢~

**Comment by wandahangFY** [comment]
已更新训练的yaml文件以及推理部分的代码，欢迎使用，有问题随时交流

**Comment by alubabaobao** [comment]
作者您好！非常感谢您的更新与分享！刚看了下，提供的hand-keypoints数据集下载链接里好像只有RGB的图片，也没有visible这个文件夹？谢谢！

**Comment by wandahangFY** [comment]
这个数据集是YOLOv8官方的数据集，仅用来测试的话，可以将可见光转成灰度图当做热红外的数据
 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:alubabaobao< ***@***.***>Date:2025-01-08 15:13:57To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Dahang Wan< ***@***.***>、Comment< ***@***.***>Subject:Re: [wandahangFY/YOLO-MIF] 请问本项目的图像融合方法适用于yolov8pose吗 (Issue #9)
作者您好！非常感谢您的更新与分享！刚看了下，提供的hand-keypoints数据集下载链接里好像只有RGB的图片，也没有visible这个文件夹？谢谢！

**Comment by alubabaobao** [comment]
我现在有RGB数据集的train和val，还有深度图像npy格式的train和val文件夹，请问应该如何安排数据集文件路径以适应 该图像融合版本的pose训练呢？

**Comment by wandahangFY** [comment]
建议做以下改动:
 1. npy格式的图像归一化到255，转成png或者bmp，与可见光后缀保持一致
2. 按照正常RGBT格式的图像布置，在Readme.md文件里面有路径格式

 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:alubabaobao< ***@***.***>Date:2025-01-08 18:04:34To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Dahang Wan< ***@***.***>、Comment< ***@***.***>Subject:Re: [wandahangFY/YOLO-MIF] 请问本项目的图像融合方法适用于yolov8pose吗 (Issue #9)
我现在有RGB数据集的train和val，还有深度图像npy格式的train和val文件夹，请问应该如何安排数据集文件路径以适应 该图像融合版本的pose训练呢？

**Comment by alubabaobao** [comment]
感谢作者的指导！成功训练后，推理的时候是输入RGB图片吗（prediect超参数仍然使用的是use_simotm="RGBT",channels=4,），出现以下报错信息：
Traceback (most recent call last):
  File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\detect-4C-pose.py", line 7, in <module>
    model.predict(source=r'D:/python project/ultralytics-main/ultralytics/datasets/5point_acupoint_rgb/images/val',
  File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\model.py", line 564, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\predictor.py", line 212, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "D:\anaconda3\envs\yolov11\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\predictor.py", line 322, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\predictor.py", line 386, in write_results
    self.plotted_img = result.plot(
  File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\results.py", line 553, in plot
    annotator.kpts(
  File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\utils\plotting.py", line 874, in kpts
    im_combined = np.concatenate((rgb1, rgb2), axis=2)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: zero-dimensional arrays cannot be concatenated

**Comment by wandahangFY** [comment]
成功训练以后，输入也是和训练时的目录一样，并且输入通道和模式保持一致。
 万达航
***@***.***
  签名由 网易灵犀办公 定制


Original:
From:alubabaobao< ***@***.***>Date:2025-01-10 21:06:33To:wandahangFY/YOLO-MIF< ***@***.***>Cc:Dahang Wan< ***@***.***>、Comment< ***@***.***>Subject:Re: [wandahangFY/YOLO-MIF] 请问本项目的图像融合方法适用于yolov8pose吗 (Issue #9)
感谢作者的指导！成功训练后，推理的时候是输入RGB图片吗（prediect超参数仍然使用的是use_simotm="RGBT",channels=4,），出现以下报错信息：
 Traceback (most recent call last):
 File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\detect-4C-pose.py", line 7, in
 model.predict(source=r'D:/python project/ultralytics-main/ultralytics/datasets/5point_acupoint_rgb/images/val',
 File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\model.py", line 564, in predict
 return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
 File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\predictor.py", line 212, in call
 return list(self.stream_inference(source, model, *args, **kwargs)) # merge list of Result into one
 File "D:\anaconda3\envs\yolov11\lib\site-packages\torch\utils_contextlib.py", line 35, in generator_context
 response = gen.send(None)
 File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\predictor.py", line 322, in stream_inference
 s[i] += self.write_results(i, Path(paths[i]), im, s)
 File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\predictor.py", line 386, in write_results
 self.plotted_img = result.plot(
 File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\engine\results.py", line 553, in plot
 annotator.kpts(
 File "D:\python project\ultralytics-8.2.79-RGBT_2025-01-08\ultralytics\utils\plotting.py", line 874, in kpts
 im_combined = np.concatenate((rgb1, rgb2), axis=2)
 File "<array_function internals>", line 180, in concatenate
 ValueError: zero-dimensional arrays cannot be concatenated
